### ISSUE TITLE
Page load extremely slow

### ISSUE THREAD

**Issue by srad** [docstrap/docstrap#143]
I don't know if this is the same as #26, but the page load takes forever with the default build.
I made the last build about a month or something ago and everything seemed fine.

**Comment by lukeapage** [comment]
@srad what protocol are you using (e.g. file/http/https)
what version of docstrap are you building?
Do you have anything public you can show?
what do you mean by "takes forever" - 100ms, 1s, 5s, 10s?
What browser? all browsers?
do you see the issue here: http://docstrap.github.io/docstrap/themes/cosmo/
do you have any non default options ?

**Comment by lukeapage** [comment]
Hi @srad can you provide any more info? I tried to reproduce and couldn't. I will reopen this if you come back with info.
