### ISSUE TITLE
Opening up each page the first time takes a lot of time

### ISSUE THREAD

**Issue by dcleao** [docstrap/docstrap#26]
Hi,

I'm using the docstrap template to generate JSDoc documentation, by using with grunt-jsdoc (and jsdoc...).

Although the documentation is all generates, opening up each page for the first time takes a lot of time (3 to 10 seconds). This happens on my local machine.
Windows 7 64bit, Chrome 31.

Do you have any idea of why this might be happening?
Do you need more information?

**Comment by stefcameron** [comment]
I have the same issue as @Flowkap. I generate docs locally in order to verify JSDoc changes, and it's just way to slow because of all these invalid "file://" URLs resulting from CSS imports, as well as, for example,

    // layout.tmpl
    

This actually isn't just a verification issue either. We deliver documentation as part of builds, and folks end-up unzipping the build locally and loading the documentation locally, so they too experience the slowness due to the invalid URLs.

Somehow providing options to individually configure the protocols to use for these URLs, or the option to force them all to "http" or "https:", for example, would make the use of generated documentation much more pleasant.

For now, I'm using my [grunt-processDocstrapDocs](https://github.com/stefcameron/grunt-processDocstrapDocs) plugin, but it really is a hack, so I'm hoping I can drop my plugin eventually...

**Comment by chevdor** [comment]
Having the same issue as @Flowkap  and @stefcameron with about 15~20s of waiting until the timeout. I am having the issue thru gulp-jsdoc.

For now, as a quick fix, I change manually the style for the theme I use.
You find it in ink-docstrap/template/styles/site.<theme>.css

In that file, you can change:
````@import url(//fonts.googleapis.com/css?family=Telex);````
into
````@import url(https://fonts.googleapis.com/css?family=Telex);````

... and enjoy all those seconds of waiting finally saved :smile: 
It is not such a great solution obviously because any update of the package will overwrite the change.
Doing this, even if your doc is on a local FS, the font is fetched online. Even w/o caching, we are talking about 30-30ms...

**Comment by chevdor** [comment]
As a sidenote, the them darkstrap comes by default with 
@import url(https://fonts.googleapis.com/css?family=Telex);

So if you like the theme, it should not show the issue atm.

**Comment by Lochemage** [comment]
You can do what I do, if you have Node.js installed:

- Install http-server with command:
  > npm install http-server -g
- Open your docs by running a local server:
  > http-server -o --cors -a localhost -p 9009

This will open the index page at localhost:9009 in your browser.

**Comment by lukeapage** [comment]
this appears fixed to me
